language: ruby
rvm:
  - 1.8.7
  - 1.9.3
before_script:
  - psql -c 'create database lowdown_test;' -U postgres
script:
  - cp config/database.yml.sample config/database.yml
  - rake db:schema:load
  - rake
